### ISSUE TITLE
Error SQL Database

### ISSUE THREAD

**Issue by lilmimemlu** [MortalSoft/CASINO-SITE#4]
I followed the steps that you wrote below the repository. But when i run the website i get this error. It cannot find a table. Maybe it requires a .sql to import in the database.

Fatal error: Uncaught Exception: Execution error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'main.info' doesn't exist in Downloads\mortal\core\classes\DataBase.class.php:55 Stack trace: #0 Downloads\mortal\core\classes\Config.class.php(10): DataBase->Execute() #1 Downloads\mortal\core\config.php(20): Config->settings() #2 Downloads\mortal\index.php(2): require_once('\\m...') #3 {main} thrown in Downloads\mortal\core\classes\DataBase.class.php on line 55

**Comment by R00tS3c** [comment]
it requires, you need to rent our API first

**Comment by lilmimemlu** [comment]
Can't it be used without the API. Means I want to use inhouse games. After some time then I can rent your api. For now I don't want slot games ?
